project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
preserve_hierarchy: true

files:
  - source: /packages/shared/src/i18n/crowdin/en.json
    translation: /packages/shared/src/i18n/crowdin/%two_letters_code%.json
    update_option: update_as_unapproved
